### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by shreesha123**

### CODE REVIEW

**Comment by ironmaniiith** [comment]
Waah re dolly, contribute kar ri he tu bhi. :stuck_out_tongue_winking_eye:

**Comment by shreesha123** [comment]
shreesha hai naam dhyaan se padh or bolna seekh ja .....popu

**Comment by ironmaniiith** [comment]
Me to ni bolunga, kya kar legi re dolly.. :sunglasses:

**Comment by shreesha123** [comment]
you will ......just wait and watch..

**Comment by ironmaniiith** [comment]
Are tu ja re, aayi badi wait and watch wali :stuck_out_tongue_winking_eye:

**Pull request merged**
